---
- name: staging playbook
  hosts: webservers
  connection: ssh
  become: true

  tasks:
    - name: installing apache on nodes
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
